In [1]:
''' 
  @Author: Uthsavi KP
  @Date: 2021-01-12 16:09:24
  @Last Modified by: Uthsavi KP
  @Last Modified time: 2021-01-12 16:09:24
  @Title: To create a 2d array with 1 on the border and 0 inside. 
'''
import numpy as np
class TwoDimensionArray:
    def create_two_dimension_array(self):
        """
        creating a 2D array with 1 on the boarder and 0 inside
        """
        two_d_array = np.array([[1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1]])
        print("Original 2D Array\n",two_d_array)
        two_d_array[1:4:1,1:4:1]=0  #[<row>,<col>]
        print("2D Array with 1 on boarder and 0 inside\n",two_d_array)
if __name__ == "__main__":
    two_dimension = TwoDimensionArray()
    two_dimension.create_two_dimension_array()

Original 2D Array
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
2D Array with 1 on boarder and 0 inside
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
