In [2]:
''' 
  @Author: Uthsavi KP
  @Date: 2021-01-12 22:36:31
  @Last Modified by: Uthsavi KP
  @Last Modified time: 2021-01-12 22:36:31
  @Title: To create a 3-D array with ones on a diagonal and zeros elsewhere.
'''
import numpy as np
class ThreeDimensionArray:
    def create_three_d_array(self):
        """
        creating a 3-D array with ones on a diagonal and zeros elsewhere.
        """
    array1 = np.identity((3))
    print(array1)
if __name__=="__main__":
    three_d_array = ThreeDimensionArray()
    three_d_array.create_three_d_array()

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
