In [4]:
''' 
  @Author: Uthsavi KP
  @Date: 2021-01-12 23:27:24
  @Last Modified by: Uthsavi KP
  @Last Modified time: 2021-01-12 23:57:31
  @Title: To add a border (filled with 0's) around an existing array. 
'''
import numpy as np
class AddBorder:
    def boarder_filled_with_zero(self):
        """
        adding border to an array with 
        0 on the border and 1 on the inside
        """
        array1 = np.random.randint(1,2,9).reshape(3,3)
        print("Original array\n",array1)        
        array = np.pad(array1, pad_width=1, mode='constant', constant_values=0) 
        print("\nArray with zero on the border\n",array)
if __name__=="__main__":
    add_border = AddBorder()
    add_border.boarder_filled_with_zero()

Original array
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

Array with zero on the border
 [[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]
