In [2]:
''' 
  @Author: Uthsavi KP
  @Date: 2021-01-13 2:08:15
  @Last Modified by: Uthsavi KP
  @Last Modified time: 2021-01-13 2:08:15
  @Title: To add an extra column to an numpy array.
'''
import numpy as np
class AddColumn:
    def add_extra_column_to_array(self):
        """
        adding an extra column to an numpy array using hstack
        """
        array1 = np.arange(10,61,10).reshape(2,3)  #array1 and array2 should have same no. of rows
        array2 = np.arange(100,201,100).reshape(2,1)
        new_array = np.hstack([array1,array2])
        print("Array one:\n",array1,"\n\nArray two:\n",array2)
        print("\nArray after adding an extra column\n",new_array)
if __name__=="__main__":
    add_column = AddColumn()
    add_column.add_extra_column_to_array()

Array one:
 [[10 20 30]
 [40 50 60]] 

Array two:
 [[100]
 [200]]

Array after adding an extra column
 [[ 10  20  30 100]
 [ 40  50  60 200]]
