In [1]:
''' 
  @Author: Uthsavi KP
  @Date: 2021-01-12 23:27:24
  @Last Modified by: Uthsavi KP
  @Last Modified time: 2021-01-12 23:57:31
  @Title: To create an 8x8 matrix and fill it with a checkboard pattern. 
'''
import numpy as np
class CheckBoard:
    def creating_checkboard_pattern(self):
        pattern = np.random.randint(0,1,64).reshape(8,8)
        print("Original matrix\n",pattern)
        pattern[1:8:2,0:7:2]=1
        pattern[0:7:2,1:8:2]=1
        print("Checkboard pattern\n",pattern)
if __name__ == "__main__":
    checkboard = CheckBoard()
    checkboard.creating_checkboard_pattern()

Original matrix
 [[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
Checkboard pattern
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
