In [1]:
''' 
  @Author: Uthsavi KP
  @Date: 2021-01-13 00:25:42
  @Last Modified by: Uthsavi KP
  @Last Modified time: 2021-01-13 00:25:42
  @Title: To concatenate two 2-dimensional arrays. 
'''
import numpy as np
class Concatenate:
    def concatenate_two_arrays(self):
        """
        concatenating two 2-dimensional arrays
        """
        array1 = np.arange(10,42,2).reshape(4,4)
        array2 = np.arange(20,60,2).reshape(4,5)
        print("Array one\n",array1,"\n\nArray two\n",array2)
        array_concat = np.concatenate((array1,array2),axis=1) #axis=0 -->rows, axis=1--.columns
        print("\nArray after concatenation\n",array_concat)    
if __name__ == "__main__":
    concat = Concatenate()
    concat.concatenate_two_arrays()

Array one
 [[10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]
 [34 36 38 40]] 

Array two
 [[20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]
 [50 52 54 56 58]]

Array after concatenation
 [[10 12 14 16 20 22 24 26 28]
 [18 20 22 24 30 32 34 36 38]
 [26 28 30 32 40 42 44 46 48]
 [34 36 38 40 50 52 54 56 58]]
