In [1]:
''' 
  @Author: Uthsavi KP
  @Date: 2021-01-12 23:27:24
  @Last Modified by: Uthsavi KP
  @Last Modified time: 2021-01-12 23:57:31
  @Title: To create a matrix with values ranging from 2 to 10. 
'''

import numpy as np
class CreateMatrix:
    def creating_matrix(self):
        #my_matrix = np.random.randint(2,11,9).reshape(3,3)
        """
        creating a matrix in the range 2 to 10 and 
        re-aranging the matrix into 3x3 matrix using numpy
        """
        matrix = np.arange(2,11).reshape(3,3)
        print(matrix)
if __name__ == "__main__":
    create_matrix = CreateMatrix()
    create_matrix.creating_matrix() 

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
