In [1]:
''' 
  @Author: Uthsavi KP
  @Date: 2021-01-12 21:29:50
  @Last Modified by: Uthsavi KP
  @Last Modified time: 2021-01-12 21:29:50
  @Title: To create a contiguous flattened array.
'''
import numpy as np
class Contiguous:
    def contiguous_flattened_array(self):
        """
        creating contiguous flattened array using ravel() method,
        it is a 2D or n-D array which is stored as a one-dimensional array
        """
        array1 = np.arange(10,26).reshape(4,4)
        print("Original_array\n",array1)
        print("\nContiguous Flattened Array\n",np.ravel(array1))
if __name__=="__main__":
    contig = Contiguous()
    contig.contiguous_flattened_array()        

Original_array
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]

Contiguous Flattened Array
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]
