In [1]:
''' 
  @Author: Uthsavi KP
  @Date: 2021-01-13 1:02:48
  @Last Modified by: Uthsavi KP
  @Last Modified time: 2021-01-13 1:02:48
  @Title: To create an array of (3, 4) shape, multiply every element value by 3 and display the new array.
'''
import numpy as np
class Multiply:
    def multiply_every_element_by_three(self):
        """
        multiplying each array element by 3
        """
        array1 = np.arange(0,12).reshape(3,4)
        print("Original array elements:\n",array1)
        print("\nNew array elements:\n",array1*3)
if __name__ == "__main__":
    multy = Multiply()
    multy.multiply_every_element_by_three()        

Original array elements:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

New array elements:
 [[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]
