In [1]:
''' 
  @Author: Uthsavi KP
  @Date: 2021-01-12 22:58:12
  @Last Modified by: Uthsavi KP
  @Last Modified time: 2021-01-12 22:58:12
  @Title: To create an array and set all the values above diagonal to zero. 
'''
import numpy as np
class CreateArray:
    def set_array_to_zero(self):
        """
        creating an array and set all the values above diagonal to zero
        """
        array1 = np.random.randint(1,2,12).reshape(4,3)
        print("Original array\n",array1)
        count = 0
        for row in array1:
            row[count:]=0
            count+=1
        print("\nArray after setting values above diagonal to zero\n",array1)    
if __name__ == "__main__":
    create_array = CreateArray()
    create_array.set_array_to_zero()

Original array
 [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

Array after setting values above diagonal to zero
 [[0 0 0]
 [1 0 0]
 [1 1 0]
 [1 1 1]]
